### ISSUE TITLE
Fix Processor::fiberEntryPoint

### ISSUE THREAD

**Issue by exjam** [exjam/wiiu-emu#20]
Nede to loop here allowing more functions to be run.

Example case:
OSGetDefaultThread(0)
OSRunThread(thread, func1)
...
<func1 exits, thread exits>
...
OSGetDefaultThread(0)
OSRunThread(thread, func2)

func2 will not run because fiberEntryPoint does not loop!

**Comment by brett19** [comment]
Instead of a loop, we should simply re-create the thread as-needed for OSRunThread or we will have lots of unused and resource-draining threads doing nothing except waiting for an OSRunThread which probably will never occur.
