### ISSUE TITLE
Really Windows 10?

### ISSUE THREAD

**Issue by therandomizer85** [exjam/wiiu-emu#39]
What kind of bullshit are you trying to pull? Why would 10 be any different from Windows 7 or 8? They're the same fucking thing, an x86-64 based OS, so how dare you alienate people?

**Comment by jojoxd** [comment]
directx 12

**Comment by therandomizer85** [comment]
That's still bullshit. Windows 10 be damned. No one should have to update to Windows 10 to play a fucking emulator.

**Comment by jojoxd** [comment]
I'm sorry, let me elaborate;

Microsoft won't update windows 7/8/8.1 and lower to directx 12.

this project is build on dx12, so it's simple math.

**Comment by therandomizer85** [comment]
It's fucking bullshit.

**Comment by exjam** [comment]
There are plans to investigate a Vulkan based renderer once it is released. Until then we will use DirectX 12, which is only supported on Windows 10.

**Comment by therandomizer85** [comment]
Yeah, yeah, whatever.

**Comment by brett19** [comment]
Thanks for the quick replying there @jojoxd.

**Comment by jojoxd** [comment]
np

**Comment by brett19** [comment]
![2015-10-09](https://cloud.githubusercontent.com/assets/1621627/10401303/8480c0dc-6e94-11e5-9f01-3cce14405afa.png)

**Comment by sasukedotca** [comment]
It's a free project done be people in their free time, you should be thankful instead of whining of OS support, we arent even at the stage in which we can talk about OS support, actually, DX 12 might help reduce overhead caused by CPU calls from the API. with weaker systems, this can really give a gain of performance..

**Comment by brett19** [comment]
Just for future reference, the reason for our choice was specifically for performance.  DirectX 12 gives us a low enough level of access to the GPU that for the most part we are able to directly translate WiiU GPU calls to DX12, this reduces the amount of overhead incurred by needing to translate between different GPU APIs.  This is also why we are primarily considering OpenGL Vulkan or Apple Metal as alternative implementations.

**Comment by RHY3756547** [comment]
Oh my god, this is the best issue I've ever seen on GitHub. Repo starred.

**Comment by TomatoHentai** [comment]
ARE YOU TRIGGERED YET?

**Comment by roflcopter777** [comment]
@TomatoHentai Yo mama was triggered ;O;
