### ISSUE TITLE
Add building instructions

### ISSUE THREAD

**Issue by VelocityRa** [exjam/wiiu-emu#53]
Opening the VS solution file (and the .vcxproj files located in the /build/ directory) is like opening a blank project, nothing is displayed. All the libraries are where they need to be.
Am I doing something wrong?
Edit: Not sure if it matters, but I'm on Win7 64bit so no DX12 support, I don't need to compile the project, just to open it in VS.

**Comment by exjam** [comment]
Are you using VS2015? Have you cloned the submodules (git submodule update --init)?

**Comment by VelocityRa** [comment]
I didn't need to, since Github for Windows took care of that. I did it anyways, but [still nothing](http://i.imgur.com/ChkcXbz.jpg)

**Comment by exjam** [comment]
Did you install VS2015 with C++ support? It is an optional install component as of vs2015.

http://blogs.msdn.com/b/vcblog/archive/2015/07/24/setup-changes-in-visual-studio-2015-affecting-c-developers.aspx

**Comment by VelocityRa** [comment]
Yup, of course. 
I also have [ReSharper C++](https://www.jetbrains.com/resharper/)...(oh crap, it's that isn't it). I mean it shouldn't cause any problems, but I should try uninstalling?

**Comment by exjam** [comment]
Well I'm all out of ideas - issue is definitely restricted to your machine, no one else (that I'm aware of) has problems opening the solution.

**Comment by VelocityRa** [comment]
Tried uninstalling all extensions (Resharper included) and repairing VS2015 to no avail.
I have idea no what the issue is, but thanks for helping (despite me not meeting the reqs), I may dual boot Windows 10 and try again.
